import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

import 'theme.dart';

TextTheme createTextTheme(
    BuildContext context, String bodyFontString, String displayFontString) {
  TextTheme baseTextTheme = Theme.of(context).textTheme;
  TextTheme bodyTextTheme = GoogleFonts.getTextTheme(bodyFontString, baseTextTheme);
  TextTheme displayTextTheme =
  GoogleFonts.getTextTheme(displayFontString, baseTextTheme);
  TextTheme textTheme = displayTextTheme.copyWith(
    bodyLarge: bodyTextTheme.bodyLarge,
    bodyMedium: bodyTextTheme.bodyMedium,
    bodySmall: bodyTextTheme.bodySmall,
    labelLarge: bodyTextTheme.labelLarge,
    labelMedium: bodyTextTheme.labelMedium,
    labelSmall: bodyTextTheme.labelSmall,
  );
  return textTheme;
}

ThemeData getTheme(context){
  TextTheme textTheme = createTextTheme(context, "Roboto", "Roboto"); // Roboto or to test "Flow Circular"
  return MyMaterialTheme(textTheme).light();
}


const hugeText = """

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum sagittis, luctus orci vitae, fermentum velit. Mauris vulputate blandit dui, eu euismod neque. Donec facilisis, augue quis pellentesque egestas, ex massa ultrices urna, eu condimentum ante risus ut est. Mauris felis enim, cursus vitae erat et, fermentum aliquet mi. Curabitur viverra, ex nec vulputate porttitor, odio metus mattis arcu, id rhoncus velit risus sed elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pulvinar, orci ac egestas sagittis, nunc tellus tristique sem, ut auctor dolor dui ut dui. Proin bibendum mauris vitae metus fermentum, sit amet sagittis arcu maximus. Vestibulum sed velit dignissim ante aliquam feugiat quis eu diam. Nulla ullamcorper leo est, ac fringilla justo fringilla quis. Sed vestibulum est felis, finibus rhoncus est aliquet nec. Duis malesuada felis in est ornare, at convallis nulla faucibus. Aenean a neque elit. Vestibulum tempus, odio at ornare euismod, metus justo tincidunt justo, ut pulvinar odio nisi et mi. Proin tincidunt sed ex id molestie. Integer faucibus non arcu suscipit facilisis.

Pellentesque pretium sodales dolor, nec interdum enim malesuada vitae. Aliquam tristique nisi vel ornare sollicitudin. Aliquam erat volutpat. Fusce facilisis eros ac nibh viverra tincidunt. Donec eget dapibus turpis, eu luctus nulla. Duis volutpat sapien ut nulla varius, eget porttitor ipsum maximus. Ut hendrerit velit dapibus, facilisis orci in, lacinia leo. Aliquam dapibus tincidunt tellus, quis tristique tortor. Maecenas pulvinar sollicitudin dolor, vel imperdiet tellus tempor sed. Praesent euismod vehicula augue, ac consectetur mi. Etiam a feugiat neque. Mauris luctus porta ligula, rhoncus pharetra orci ullamcorper nec. Ut aliquam, tortor id volutpat convallis, erat ipsum scelerisque enim, eget dictum augue magna nec ante. Sed nulla sapien, accumsan et tortor eu, ultrices imperdiet orci. Aliquam vel massa orci.

Suspendisse id enim eget dui ultrices tempor vitae ac velit. Duis at neque sed arcu vulputate venenatis at eu mi. Duis vel ligula nisl. Suspendisse pharetra vitae ligula ac imperdiet. Ut lacinia sapien est, sed placerat velit aliquam eget. Integer pretium velit eu nisi maximus posuere. Donec ultricies libero mauris, non cursus lectus cursus non. Nullam condimentum, nunc ac volutpat molestie, lacus turpis faucibus purus, eget tincidunt lectus magna sit amet erat. Nulla arcu tellus, rutrum vel semper sit amet, tincidunt ac sem. Quisque efficitur, velit sit amet sollicitudin sodales, ipsum nulla rhoncus quam, tincidunt molestie erat lectus nec est. Phasellus nibh magna, efficitur et massa id, ultricies ornare elit.

Mauris vel ligula in augue ultrices ullamcorper. Vestibulum cursus ac augue eget tempor. Morbi sapien tellus, rhoncus tristique ornare eget, tincidunt ac dolor. Nullam facilisis nec dui eget volutpat. Maecenas lobortis enim leo, ornare laoreet nulla imperdiet ut. Mauris rhoncus vitae odio quis egestas. Morbi convallis leo ex, dapibus molestie enim congue ac. Vestibulum sed ultrices lectus, ut venenatis ligula.

Etiam at interdum lorem. Nam diam tortor, lobortis vitae eros quis, aliquet vulputate nisl. Phasellus fermentum mauris et accumsan semper. Proin nec mattis tortor. Suspendisse luctus vehicula mauris, vitae tempor lorem rutrum porta. Nulla hendrerit fermentum turpis. Nam sodales dapibus tellus ut iaculis. Duis sed fermentum turpis. Nam posuere quam porttitor suscipit lobortis. Donec tincidunt mauris nec felis vulputate, eget hendrerit ante tempus. 

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum sagittis, luctus orci vitae, fermentum velit. Mauris vulputate blandit dui, eu euismod neque. Donec facilisis, augue quis pellentesque egestas, ex massa ultrices urna, eu condimentum ante risus ut est. Mauris felis enim, cursus vitae erat et, fermentum aliquet mi. Curabitur viverra, ex nec vulputate porttitor, odio metus mattis arcu, id rhoncus velit risus sed elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pulvinar, orci ac egestas sagittis, nunc tellus tristique sem, ut auctor dolor dui ut dui. Proin bibendum mauris vitae metus fermentum, sit amet sagittis arcu maximus. Vestibulum sed velit dignissim ante aliquam feugiat quis eu diam. Nulla ullamcorper leo est, ac fringilla justo fringilla quis. Sed vestibulum est felis, finibus rhoncus est aliquet nec. Duis malesuada felis in est ornare, at convallis nulla faucibus. Aenean a neque elit. Vestibulum tempus, odio at ornare euismod, metus justo tincidunt justo, ut pulvinar odio nisi et mi. Proin tincidunt sed ex id molestie. Integer faucibus non arcu suscipit facilisis.

Pellentesque pretium sodales dolor, nec interdum enim malesuada vitae. Aliquam tristique nisi vel ornare sollicitudin. Aliquam erat volutpat. Fusce facilisis eros ac nibh viverra tincidunt. Donec eget dapibus turpis, eu luctus nulla. Duis volutpat sapien ut nulla varius, eget porttitor ipsum maximus. Ut hendrerit velit dapibus, facilisis orci in, lacinia leo. Aliquam dapibus tincidunt tellus, quis tristique tortor. Maecenas pulvinar sollicitudin dolor, vel imperdiet tellus tempor sed. Praesent euismod vehicula augue, ac consectetur mi. Etiam a feugiat neque. Mauris luctus porta ligula, rhoncus pharetra orci ullamcorper nec. Ut aliquam, tortor id volutpat convallis, erat ipsum scelerisque enim, eget dictum augue magna nec ante. Sed nulla sapien, accumsan et tortor eu, ultrices imperdiet orci. Aliquam vel massa orci.

Suspendisse id enim eget dui ultrices tempor vitae ac velit. Duis at neque sed arcu vulputate venenatis at eu mi. Duis vel ligula nisl. Suspendisse pharetra vitae ligula ac imperdiet. Ut lacinia sapien est, sed placerat velit aliquam eget. Integer pretium velit eu nisi maximus posuere. Donec ultricies libero mauris, non cursus lectus cursus non. Nullam condimentum, nunc ac volutpat molestie, lacus turpis faucibus purus, eget tincidunt lectus magna sit amet erat. Nulla arcu tellus, rutrum vel semper sit amet, tincidunt ac sem. Quisque efficitur, velit sit amet sollicitudin sodales, ipsum nulla rhoncus quam, tincidunt molestie erat lectus nec est. Phasellus nibh magna, efficitur et massa id, ultricies ornare elit.

Mauris vel ligula in augue ultrices ullamcorper. Vestibulum cursus ac augue eget tempor. Morbi sapien tellus, rhoncus tristique ornare eget, tincidunt ac dolor. Nullam facilisis nec dui eget volutpat. Maecenas lobortis enim leo, ornare laoreet nulla imperdiet ut. Mauris rhoncus vitae odio quis egestas. Morbi convallis leo ex, dapibus molestie enim congue ac. Vestibulum sed ultrices lectus, ut venenatis ligula.

Etiam at interdum lorem. Nam diam tortor, lobortis vitae eros quis, aliquet vulputate nisl. Phasellus fermentum mauris et accumsan semper. Proin nec mattis tortor. Suspendisse luctus vehicula mauris, vitae tempor lorem rutrum porta. Nulla hendrerit fermentum turpis. Nam sodales dapibus tellus ut iaculis. Duis sed fermentum turpis. Nam posuere quam porttitor suscipit lobortis. Donec tincidunt mauris nec felis vulputate, eget hendrerit ante tempus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum sagittis, luctus orci vitae, fermentum velit. Mauris vulputate blandit dui, eu euismod neque. Donec facilisis, augue quis pellentesque egestas, ex massa ultrices urna, eu condimentum ante risus ut est. Mauris felis enim, cursus vitae erat et, fermentum aliquet mi. Curabitur viverra, ex nec vulputate porttitor, odio metus mattis arcu, id rhoncus velit risus sed elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pulvinar, orci ac egestas sagittis, nunc tellus tristique sem, ut auctor dolor dui ut dui. Proin bibendum mauris vitae metus fermentum, sit amet sagittis arcu maximus. Vestibulum sed velit dignissim ante aliquam feugiat quis eu diam. Nulla ullamcorper leo est, ac fringilla justo fringilla quis. Sed vestibulum est felis, finibus rhoncus est aliquet nec. Duis malesuada felis in est ornare, at convallis nulla faucibus. Aenean a neque elit. Vestibulum tempus, odio at ornare euismod, metus justo tincidunt justo, ut pulvinar odio nisi et mi. Proin tincidunt sed ex id molestie. Integer faucibus non arcu suscipit facilisis.

Pellentesque pretium sodales dolor, nec interdum enim malesuada vitae. Aliquam tristique nisi vel ornare sollicitudin. Aliquam erat volutpat. Fusce facilisis eros ac nibh viverra tincidunt. Donec eget dapibus turpis, eu luctus nulla. Duis volutpat sapien ut nulla varius, eget porttitor ipsum maximus. Ut hendrerit velit dapibus, facilisis orci in, lacinia leo. Aliquam dapibus tincidunt tellus, quis tristique tortor. Maecenas pulvinar sollicitudin dolor, vel imperdiet tellus tempor sed. Praesent euismod vehicula augue, ac consectetur mi. Etiam a feugiat neque. Mauris luctus porta ligula, rhoncus pharetra orci ullamcorper nec. Ut aliquam, tortor id volutpat convallis, erat ipsum scelerisque enim, eget dictum augue magna nec ante. Sed nulla sapien, accumsan et tortor eu, ultrices imperdiet orci. Aliquam vel massa orci.

Suspendisse id enim eget dui ultrices tempor vitae ac velit. Duis at neque sed arcu vulputate venenatis at eu mi. Duis vel ligula nisl. Suspendisse pharetra vitae ligula ac imperdiet. Ut lacinia sapien est, sed placerat velit aliquam eget. Integer pretium velit eu nisi maximus posuere. Donec ultricies libero mauris, non cursus lectus cursus non. Nullam condimentum, nunc ac volutpat molestie, lacus turpis faucibus purus, eget tincidunt lectus magna sit amet erat. Nulla arcu tellus, rutrum vel semper sit amet, tincidunt ac sem. Quisque efficitur, velit sit amet sollicitudin sodales, ipsum nulla rhoncus quam, tincidunt molestie erat lectus nec est. Phasellus nibh magna, efficitur et massa id, ultricies ornare elit.

Mauris vel ligula in augue ultrices ullamcorper. Vestibulum cursus ac augue eget tempor. Morbi sapien tellus, rhoncus tristique ornare eget, tincidunt ac dolor. Nullam facilisis nec dui eget volutpat. Maecenas lobortis enim leo, ornare laoreet nulla imperdiet ut. Mauris rhoncus vitae odio quis egestas. Morbi convallis leo ex, dapibus molestie enim congue ac. Vestibulum sed ultrices lectus, ut venenatis ligula.

Etiam at interdum lorem. Nam diam tortor, lobortis vitae eros quis, aliquet vulputate nisl. Phasellus fermentum mauris et accumsan semper. Proin nec mattis tortor. Suspendisse luctus vehicula mauris, vitae tempor lorem rutrum porta. Nulla hendrerit fermentum turpis. Nam sodales dapibus tellus ut iaculis. Duis sed fermentum turpis. Nam posuere quam porttitor suscipit lobortis. Donec tincidunt mauris nec felis vulputate, eget hendrerit ante tempus.


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum sagittis, luctus orci vitae, fermentum velit. Mauris vulputate blandit dui, eu euismod neque. Donec facilisis, augue quis pellentesque egestas, ex massa ultrices urna, eu condimentum ante risus ut est. Mauris felis enim, cursus vitae erat et, fermentum aliquet mi. Curabitur viverra, ex nec vulputate porttitor, odio metus mattis arcu, id rhoncus velit risus sed elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris pulvinar, orci ac egestas sagittis, nunc tellus tristique sem, ut auctor dolor dui ut dui. Proin bibendum mauris vitae metus fermentum, sit amet sagittis arcu maximus. Vestibulum sed velit dignissim ante aliquam feugiat quis eu diam. Nulla ullamcorper leo est, ac fringilla justo fringilla quis. Sed vestibulum est felis, finibus rhoncus est aliquet nec. Duis malesuada felis in est ornare, at convallis nulla faucibus. Aenean a neque elit. Vestibulum tempus, odio at ornare euismod, metus justo tincidunt justo, ut pulvinar odio nisi et mi. Proin tincidunt sed ex id molestie. Integer faucibus non arcu suscipit facilisis.

Pellentesque pretium sodales dolor, nec interdum enim malesuada vitae. Aliquam tristique nisi vel ornare sollicitudin. Aliquam erat volutpat. Fusce facilisis eros ac nibh viverra tincidunt. Donec eget dapibus turpis, eu luctus nulla. Duis volutpat sapien ut nulla varius, eget porttitor ipsum maximus. Ut hendrerit velit dapibus, facilisis orci in, lacinia leo. Aliquam dapibus tincidunt tellus, quis tristique tortor. Maecenas pulvinar sollicitudin dolor, vel imperdiet tellus tempor sed. Praesent euismod vehicula augue, ac consectetur mi. Etiam a feugiat neque. Mauris luctus porta ligula, rhoncus pharetra orci ullamcorper nec. Ut aliquam, tortor id volutpat convallis, erat ipsum scelerisque enim, eget dictum augue magna nec ante. Sed nulla sapien, accumsan et tortor eu, ultrices imperdiet orci. Aliquam vel massa orci.

Suspendisse id enim eget dui ultrices tempor vitae ac velit. Duis at neque sed arcu vulputate venenatis at eu mi. Duis vel ligula nisl. Suspendisse pharetra vitae ligula ac imperdiet. Ut lacinia sapien est, sed placerat velit aliquam eget. Integer pretium velit eu nisi maximus posuere. Donec ultricies libero mauris, non cursus lectus cursus non. Nullam condimentum, nunc ac volutpat molestie, lacus turpis faucibus purus, eget tincidunt lectus magna sit amet erat. Nulla arcu tellus, rutrum vel semper sit amet, tincidunt ac sem. Quisque efficitur, velit sit amet sollicitudin sodales, ipsum nulla rhoncus quam, tincidunt molestie erat lectus nec est. Phasellus nibh magna, efficitur et massa id, ultricies ornare elit.

Mauris vel ligula in augue ultrices ullamcorper. Vestibulum cursus ac augue eget tempor. Morbi sapien tellus, rhoncus tristique ornare eget, tincidunt ac dolor. Nullam facilisis nec dui eget volutpat. Maecenas lobortis enim leo, ornare laoreet nulla imperdiet ut. Mauris rhoncus vitae odio quis egestas. Morbi convallis leo ex, dapibus molestie enim congue ac. Vestibulum sed ultrices lectus, ut venenatis ligula.

Etiam at interdum lorem. Nam diam tortor, lobortis vitae eros quis, aliquet vulputate nisl. Phasellus fermentum mauris et accumsan semper. Proin nec mattis tortor. Suspendisse luctus vehicula mauris, vitae tempor lorem rutrum porta. Nulla hendrerit fermentum turpis. Nam sodales dapibus tellus ut iaculis. Duis sed fermentum turpis. Nam posuere quam porttitor suscipit lobortis. Donec tincidunt mauris nec felis vulputate, eget hendrerit ante tempus.

""";